from .configuration_utils import PreTrainedConfig as PreTrainedConfig
from typing import Any

logger: Any
BERT_PRETRAINED_CONFIG_ARCHIVE_MAP: Any

class BertConfig(PreTrainedConfig):
    model_type: str = ...
    # vocab_size: Any = ...
    hidden_size: int = ...
    num_hidden_layers: int = ...
    num_attention_heads: int = ...
    # hidden_act: Any = ...
    intermediate_size: int = ...
    hidden_dropout_prob: float = ...
    attention_probs_dropout_prob: float = ...
    max_position_embeddings: int = ...
    # type_vocab_size: Any = ...
    # initializer_range: Any = ...
    layer_norm_eps: int = ...
    # gradient_checkpointing: Any = ...
    def __init__(
        self,
        vocab_size: int = ...,
        hidden_size: int = ...,
        num_hidden_layers: int = ...,
        num_attention_heads: int = ...,
        intermediate_size: int = ...,
        hidden_act: str = ...,
        hidden_dropout_prob: float = ...,
        attention_probs_dropout_prob: float = ...,
        max_position_embeddings: int = ...,
        type_vocab_size: int = ...,
        initializer_range: float = ...,
        layer_norm_eps: float = ...,
        pad_token_id: int = ...,
        gradient_checkpointing: bool = ...,
        **kwargs: Any
    ) -> None: ...
