import typing

class PretrainedConfig:
    model_type: str = ...
    #    return_dict: Any = ...
    #    output_hidden_states: Any = ...
    #    output_attentions: Any = ...
    #    use_cache: Any = ...
    #    torchscript: Any = ...
    #    use_bfloat16: Any = ...
    #    pruned_heads: Any = ...
    #    is_encoder_decoder: Any = ...
    #    is_decoder: Any = ...
    #    max_length: Any = ...
    #    min_length: Any = ...
    #    do_sample: Any = ...
    #    early_stopping: Any = ...
    #    num_beams: Any = ...
    #    temperature: Any = ...
    #    top_k: Any = ...
    #    top_p: Any = ...
    #    repetition_penalty: Any = ...
    #    length_penalty: Any = ...
    #    no_repeat_ngram_size: Any = ...
    #    bad_words_ids: Any = ...
    #    num_return_sequences: Any = ...
    #    architectures: Any = ...
    #    finetuning_task: Any = ...
    #    id2label: Any = ...
    #    label2id: Any = ...
    #    prefix: Any = ...
    #    bos_token_id: Any = ...
    #    pad_token_id: Any = ...
    #    eos_token_id: Any = ...
    #    decoder_start_token_id: Any = ...
    #    task_specific_params: Any = ...
    #    xla_device: Any = ...
