

from typing import Any, Tuple
from typing_extensions import OrderedDict


def is_torch_available() -> bool: ...
def is_tf_available() -> bool: ...
def is_torch_tpu_available() -> bool: ...
def is_psutil_available() -> bool: ...
def is_py3nvml_available() -> bool: ...
def is_apex_available() -> bool: ...

class ModelOutput(OrderedDict):
    def to_tuple(self) -> Tuple[Any, ...]: ...
