def is_torch_available() -> bool: ...
def is_tf_available() -> bool: ...
def is_torch_tpu_available() -> bool: ...
def is_psutil_available() -> bool: ...
def is_py3nvml_available() -> bool: ...
def is_apex_available() -> bool: ...
